const STATES = {
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
  CONFIRMED: "CONFIRMED",
  NOT_COMPLETE: "NOT_COMPLETE",
  DISPATCHED: "DISPATCHED",
  NOT_SELECTED: "NOT_SELECTED",
};

module.exports = { STATES };
